//! Raster surfacing toolpath generation.
//!
//! Produces rectangular surfacing passes with configurable angle, stepover,
//! depth strategy, and travel origin.

#[derive(Debug)]
/// Parameters controlling surfacing toolpath generation.
pub struct SurfacingParams {
    pub width: f32,
    pub height: f32,
    pub total_depth: f32,
    pub depth_per_pass: f32,
    pub stepover: f32,
    pub angle_deg: f32,
    pub overtravel: f32,
    pub bidirectional: bool,
    pub safe_z: f32,
    pub feedrate: f32,
    pub plunge_rate: f32,
    pub spindle_rpm: u32,
    pub finish_pass: bool,
    pub use_inches: bool,
    pub origin: String,
}

fn rotate(x: f32, y: f32, angle_rad: f32) -> (f32, f32) {
    let c = angle_rad.cos();
    let s = angle_rad.sin();
    (c * x - s * y, s * x + c * y)
}

fn clip_line(
    x0: f32,
    y0: f32,
    x1: f32,
    y1: f32,
    xmin: f32,
    xmax: f32,
    ymin: f32,
    ymax: f32,
) -> Option<((f32, f32), (f32, f32))> {
    let dx = x1 - x0;
    let dy = y1 - y0;
    let mut t0: f32 = 0.0;
    let mut t1: f32 = 1.0;

    for (p, q) in [(-dx, x0 - xmin), (dx, xmax - x0), (-dy, y0 - ymin), (dy, ymax - y0)] {
        if p == 0.0 {
            if q < 0.0 {
                return None;
            }
        } else {
            let r = q / p;
            if p < 0.0 {
                if r > t1 {
                    return None;
                }
                if r > t0 {
                    t0 = r;
                }
            } else {
                if r < t0 {
                    return None;
                }
                if r < t1 {
                    t1 = r;
                }
            }
        }
    }

    Some(((x0 + t0 * dx, y0 + t0 * dy), (x0 + t1 * dx, y0 + t1 * dy)))
}

/// Generate G-code for a surfacing raster from validated parameters.
///
/// # Errors
/// Returns an error when any required numeric parameter is non-positive.
pub fn build_surfacing_gcode(p: &SurfacingParams) -> Result<String, String> {
    if p.width <= 0.0 {
        return Err("width must be > 0".into());
    }
    if p.height <= 0.0 {
        return Err("height must be > 0".into());
    }
    if p.total_depth <= 0.0 {
        return Err("total_depth must be > 0".into());
    }
    if p.depth_per_pass <= 0.0 {
        return Err("depth_per_pass must be > 0".into());
    }
    if p.stepover <= 0.0 {
        return Err("stepover must be > 0".into());
    }
    if p.feedrate <= 0.0 {
        return Err("feedrate must be > 0".into());
    }
    if p.plunge_rate <= 0.0 {
        return Err("plunge_rate must be > 0".into());
    }

    let unit_cmd = if p.use_inches { "G20" } else { "G21" };
    let num_passes = (p.total_depth / p.depth_per_pass).ceil() as u32;

    let angle_rad = p.angle_deg.to_radians();
    let inv_rad = -angle_rad;

    let (x_off, y_off): (f32, f32) = match p.origin.as_str() {
        "front_right" => (-p.width, 0.0),
        "back_left" => (0.0, -p.height),
        "back_right" => (-p.width, -p.height),
        "center" => (-p.width / 2.0, -p.height / 2.0),
        _ => (0.0, 0.0),
    };

    let corners_world = [
        (x_off - p.overtravel, y_off - p.overtravel),
        (x_off + p.width + p.overtravel, y_off - p.overtravel),
        (x_off + p.width + p.overtravel, y_off + p.height + p.overtravel),
        (x_off - p.overtravel, y_off + p.height + p.overtravel),
    ];

    let rotated: Vec<(f32, f32)> = corners_world
        .iter()
        .map(|&(x, y)| rotate(x, y, inv_rad))
        .collect();

    let scan_x_min = rotated.iter().map(|&(x, _)| x).fold(f32::INFINITY, f32::min);
    let scan_x_max = rotated
        .iter()
        .map(|&(x, _)| x)
        .fold(f32::NEG_INFINITY, f32::max);
    let scan_y_min = rotated.iter().map(|&(_, y)| y).fold(f32::INFINITY, f32::min);
    let scan_y_max = rotated
        .iter()
        .map(|&(_, y)| y)
        .fold(f32::NEG_INFINITY, f32::max);

    let clip_xmin = x_off - p.overtravel;
    let clip_xmax = x_off + p.width + p.overtravel;
    let clip_ymin = y_off - p.overtravel;
    let clip_ymax = y_off + p.height + p.overtravel;

    let mut out = String::with_capacity(4096);

    out.push_str("; Raster surfacing - generated by gTaurus standalone server\n");
    out.push_str(&format!(
        "; Stock: {:.3} x {:.3}  Depth: {:.3}  Passes: {}\n",
        p.width, p.height, p.total_depth, num_passes
    ));
    out.push_str(&format!(
        "; Step-over: {:.3}  Angle: {:.1}deg  {}\n",
        p.stepover,
        p.angle_deg,
        if p.bidirectional {
            "Bidirectional"
        } else {
            "Unidirectional"
        }
    ));
    out.push_str(&format!("{} G90 G94\n", unit_cmd));
    out.push_str(&format!("M3 S{}\n", p.spindle_rpm));
    out.push_str(&format!("G0 Z{:.4}\n", p.safe_z));

    let total_passes = if p.finish_pass {
        num_passes + 1
    } else {
        num_passes
    };

    for pass in 1..=total_passes {
        let cut_z = if p.finish_pass && pass == total_passes {
            -(p.total_depth + 0.05_f32)
        } else {
            -((pass as f32 * p.depth_per_pass).min(p.total_depth))
        };

        out.push_str(&format!("; Pass {} - Z{:.4}\n", pass, cut_z));

        let span = scan_y_max - scan_y_min;
        let num_lines = (span / p.stepover).floor() as u32;
        let start_offset = (span - (num_lines as f32 * p.stepover)) / 2.0;
        let mut y_scan = scan_y_min + start_offset;
        let mut line_idx: u32 = 0;

        while y_scan <= scan_y_max + 1e-4 {
            let forward = !p.bidirectional || (line_idx % 2 == 0);

            let (sx_scan, ex_scan) = if forward {
                (scan_x_min, scan_x_max)
            } else {
                (scan_x_max, scan_x_min)
            };

            let (sx, sy) = rotate(sx_scan, y_scan, angle_rad);
            let (ex, ey) = rotate(ex_scan, y_scan, angle_rad);

            if let Some(((csx, csy), (cex, cey))) =
                clip_line(sx, sy, ex, ey, clip_xmin, clip_xmax, clip_ymin, clip_ymax)
            {
                out.push_str(&format!("G0 X{:.4} Y{:.4} Z{:.4}\n", csx, csy, p.safe_z));
                out.push_str(&format!("G1 Z{:.4} F{:.1}\n", cut_z, p.plunge_rate));
                out.push_str(&format!("G1 X{:.4} Y{:.4} F{:.1}\n", cex, cey, p.feedrate));

                if !p.bidirectional {
                    out.push_str(&format!("G0 Z{:.4}\n", p.safe_z));
                }
            }

            y_scan += p.stepover;
            line_idx += 1;
        }

        out.push_str(&format!("G0 Z{:.4}\n", p.safe_z));
    }

    out.push_str("M5\n");
    out.push_str("M30\n");

    Ok(out)
}

/// Convenience constructor + generator using scalar arguments.
///
/// Builds a [`SurfacingParams`] instance and delegates to [`build_surfacing_gcode`].
pub fn generate_surfacing_toolpath(
    width: f32,
    height: f32,
    total_depth: f32,
    depth_per_pass: f32,
    stepover: f32,
    angle_deg: f32,
    overtravel: f32,
    bidirectional: bool,
    safe_z: f32,
    feedrate: f32,
    plunge_rate: f32,
    spindle_rpm: u32,
    finish_pass: bool,
    use_inches: bool,
    origin: String,
) -> Result<String, String> {
    let params = SurfacingParams {
        width,
        height,
        total_depth,
        depth_per_pass,
        stepover,
        angle_deg,
        overtravel,
        bidirectional,
        safe_z,
        feedrate,
        plunge_rate,
        spindle_rpm,
        finish_pass,
        use_inches,
        origin,
    };
    build_surfacing_gcode(&params)
}
